rsocket-core/src/main/java/io/rsocket/RSocketClient.kt
rsocket-core/src/main/java/io/rsocket/RSocketServer.kt
rsocket-core/src/main/java/io/rsocket/internal/LimitedRequestPublisher.kt
rsocket-server-netty/build.gradle
rsocket-server-netty/src/main/java/io/rsocket/transport/netty/sampleserver/Server.kt

Reverts rsocket/rsocket-android#7

Revert "Introduce request-channel support for Requester and Responder RSockets"

---

rsocket-transport-okhttp/src/main/java/io/rsocket/transport/okhttp/OkhttpWebsocketConnection.kt
rsocket-transport-okhttp/src/main/java/io/rsocket/transport/okhttp/client/OkhttpWebsocketClientTransport.kt

fixes and enhancements as described in commit messages

OkHttp transport updates

---

rsocket-core/src/main/java/io/rsocket/android/RSocketClient.kt
rsocket-core/src/main/java/io/rsocket/android/RSocketFactory.kt
rsocket-core/src/main/java/io/rsocket/android/RSocketServer.kt
rsocket-core/src/test/java/io/rsocket/android/RSocketClientTest.kt
rsocket-core/src/test/java/io/rsocket/android/RequesterStreamWindowTest.kt
rsocket-core/src/test/java/io/rsocket/android/ResponderStreamWindowTest.kt

relates to rsocket/rsocket-java#399

limit streams demand for request-stream and request-channel

---

README.md
build.gradle
rsocket-transport-okhttp/build.gradle

Also updated readme with bintray snapshots info

Versions bump

---

README.md
build.gradle
rsocket-core/src/main/kotlin/io/rsocket/kotlin/DefaultPayload.kt
rsocket-core/src/main/kotlin/io/rsocket/kotlin/internal/FrameSender.kt
rsocket-core/src/main/kotlin/io/rsocket/kotlin/internal/FrameUnicastProcessor.kt
rsocket-core/src/main/kotlin/io/rsocket/kotlin/internal/RSocketRequester.kt
rsocket-core/src/main/kotlin/io/rsocket/kotlin/internal/RSocketResponder.kt
rsocket-core/src/test/kotlin/io/rsocket/kotlin/frame/SetupFrameTest.kt
rsocket-core/src/test/kotlin/io/rsocket/kotlin/internal/ConnectionDemuxerTest.kt
rsocket-core/src/test/kotlin/io/rsocket/kotlin/internal/FrameSenderTest.kt
rsocket-core/src/test/kotlin/io/rsocket/kotlin/util/DefaultPayloadTest.kt
test/src/test/kotlin/io/rsocket/kotlin/test/InteractionsStressTest.kt
test/src/test/kotlin/io/rsocket/kotlin/test/transport/ClientServerChannelTest.kt
test/src/test/kotlin/io/rsocket/kotlin/test/transport/EndToEndTest.kt

* Introduce FrameSender which releases queued frames on cancel/termination 
* Basic interactions stress tests
* cleanup readme

Introduce FrameSender which releases queued frames on cancel/termination

---

rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/connection/LoggingConnection.kt
rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/core/RSocketConnector.kt
rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/core/RSocketConnectorConfiguration.kt
rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/core/RSocketServer.kt
rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/core/RSocketServerConfiguration.kt
rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/frame/ErrorFrame.kt
rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/frame/ExtensionFrame.kt
rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/frame/Frame.kt
rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/frame/KeepAliveFrame.kt
rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/frame/LeaseFrame.kt
rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/frame/MetadataPushFrame.kt
rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/frame/RequestFrame.kt
rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/frame/RequestNFrame.kt
rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/frame/ResumeFrame.kt
rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/frame/ResumeOkFrame.kt
rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/frame/SetupFrame.kt
rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/frame/io/Dump.kt
rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/logging/Logging.kt
rsocket-core/src/jsMain/kotlin/io/rsocket/kotlin/logging/DefaultLoggerFactory.kt
rsocket-core/src/jvmMain/kotlin/io/rsocket/kotlin/logging/DefaultLoggerFactory.kt
rsocket-core/src/jvmTest/kotlin/io/rsocket/kotlin/Test.kt
rsocket-core/src/jvmTest/resources/logging.properties
rsocket-transport-ktor/rsocket-transport-ktor-client/src/commonMain/kotlin/io/rsocket/kotlin/core/RSocketClientSupport.kt
rsocket-transport-ktor/rsocket-transport-ktor-server/src/jvmMain/kotlin/io/rsocket/kotlin/core/RSocketServerSupport.kt
rsocket-transport-test/src/commonMain/kotlin/io/rsocket/kotlin/TransportTest.kt

Provides frame logging (with handwritten hex dump) closes #96

Minimal logging support, debug frame dump logging

---

rsocket-core/build.gradle.kts
rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/internal/flow/RequestChannelRequesterFlow.kt
rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/internal/flow/RequestChannelResponderFlow.kt
rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/internal/flow/RequestStreamRequesterFlow.kt
rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/internal/flow/StreamFlow.kt
rsocket-core/src/commonTest/kotlin/io/rsocket/kotlin/Test.common.kt
rsocket-core/src/commonTest/kotlin/io/rsocket/kotlin/internal/RSocketRequesterTest.kt
rsocket-core/src/jsTest/kotlin/io/rsocket/kotlin/Test.kt
rsocket-core/src/jvmTest/kotlin/io/rsocket/kotlin/Test.kt

Fix sending redundant RequestN frame

---

.github/workflows/gradle-all.yml
.github/workflows/gradle-main.yml
.github/workflows/gradle-pr.yml
.github/workflows/gradle-release.yml

Old api is deprecated, so publication is failing

Replace set-env with new gh API

---

benchmarks/build.gradle.kts
build.gradle.kts
examples/multiplatform-chat/build.gradle.kts
examples/nodejs-tcp-transport/build.gradle.kts
gradle.properties
settings.gradle.kts

* Extract all versions to gradle.properties
* Remove workaround for publishing
* Remove not needed logic in root build.gradle.kts

Gradle cleanup

---

rsocket-transport-ktor/src/jvmMain/kotlin/io/rsocket/kotlin/transport/ktor/TcpServerTransport.kt
rsocket-transport-ktor/src/jvmTest/kotlin/io/rsocket/kotlin/TcpServerTest.kt

fix tcp server fail

---

rsocket-transport-ktor/src/commonMain/kotlin/io/rsocket/kotlin/transport/ktor/WebSocketConnection.kt
rsocket-transport-ktor/src/jvmTest/kotlin/io/rsocket/kotlin/WebSocketConnectionTest.kt

add workaround for ktor-io issue

---

rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/RSocketError.kt
rsocket-core/src/commonTest/kotlin/io/rsocket/kotlin/RSocketCustomErrorTest.kt

make RSocketError.Custom.errorCode usable

---

gradle.properties
rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/internal/CloseOperations.kt
rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/internal/Prioritizer.kt
rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/internal/RSocketResponder.kt
rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/internal/RSocketState.kt
rsocket-transport-local/src/commonMain/kotlin/io/rsocket/kotlin/transport/local/LocalServer.kt

* coroutines 1.4.3 + related dependencies update
* remove workaround for coroutines bug

Сoroutines 1.4.3

---

rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/RSocketRequestHandler.kt

Discussion from https://github.com/rsocket/rsocket-kotlin/issues/143

Suspend methods in RSocketRequestHandlerBuilder

---

README.md

```
➜  ~ rsocket-cli wss://demo.rsocket.io/rsocket
0
1
2
3
^C
```

Update README.md to demo.rsocket.io

---

README.md

Dependencies upgraded in `README.md` file
Had an issue in pet-project, while building `rsocket-kotlin`, figured out that examples were outdated
Changed deps in `README.md`
With this "numbers" build are fixes in my own project

upgrades dependencies in documentation

---

buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/targetsJvm.kt

Setup jvm toolchain
* compile using JDK 8
* able to run tests on both JDK 8 and 17
Depends on #199

Jvm toolchain

---

.github/workflows/publish-snapshot.yml

_[One line description of your change]_
_[Explain here the context, and why you're making that change. What is the problem you're trying to solve.]_
_[Describe the modifications you've done.]_
_[After your change, what will change.]_

Snapshot workflow fix

---

.github/workflows/ci-release.yml
README.md
buildSrc/src/main/kotlin/rsocket.publication.gradle.kts
gradle.properties

* set version 0.15.4 in readme
* revert intrusive changes for publications to maven central
* set version 0.16.0 in project

cleanup after release

---

.github/workflows/run-tests.yml
buildSrc/src/main/kotlin/targetsJs.kt
buildSrc/src/main/kotlin/targetsNative.kt
gradle.properties
gradle/js/yarn/yarn.lock
gradle/libs.updates.gradle.kts
gradle/libs.versions.toml
rsocket-transport-ktor/rsocket-transport-ktor-websocket-client/build.gradle.kts
settings.gradle.kts

* kotlin 1.8.21
* coroutines 1.6.4
* ktor 2.3.0
* extract version updates to separate script

Update to latest dependencies versions:

---

.github/actions/setup-gradle/action.yml
.github/workflows/ci-samples.yml
.github/workflows/publish-release.yml
.github/workflows/publish-snapshot.yml
.github/workflows/run-tests.yml

* use arm macos on CI
* update versions of actions
* minor cleanup

Actualize workflows

---

gradle/libs.versions.toml
rsocket-transports/ktor-tcp/src/commonMain/kotlin/io/rsocket/kotlin/transport/ktor/tcp/KtorTcpConnection.kt

ktor 3.0.2 fixes https://youtrack.jetbrains.com/issue/KTOR-7746

Update ktor to 3.0.2
