rsocket/rsocket-kotlin

- rsocket-core/src/main/java/io/rsocket/RSocketClient.kt
- rsocket-core/src/main/java/io/rsocket/RSocketServer.kt
- rsocket-core/src/main/java/io/rsocket/internal/LimitableRequestPublisher.kt
- rsocket-server-netty/build.gradle
- rsocket-server-netty/src/main/java/io/rsocket/transport/netty/sampleserver/Server.kt
Closes  #4. For now `UnboundedProcessor` not implemented, substituted by `PublishProcessor`. Need to check whether still an issue for mobile use case. Verified with tests in #9 and sample mobile application
> Introduce request-channel support for Requester and Responder RSockets

- rsocket-core/src/main/java/io/rsocket/android/RSocketClient.kt
- rsocket-core/src/test/java/io/rsocket/android/RSocketClientTest.kt
Fixes to RSocket requester
* fix bug when RSocket requester streams do not get terminal signal on connection close
*  after connection close, new RSocketClient requests were not getting error signal, hang indefinetely
> Upstream bug fixes

- build.gradle
This change is an attempt to restore Artifactory snapshots publication
> Restore artifactory snapshots publication

- gradle.properties
- rsocket-core/src/main/kotlin/io/rsocket/kotlin/internal/RSocketRequester.kt
- rsocket-core/src/main/kotlin/io/rsocket/kotlin/internal/RSocketResponder.kt
- rsocket-core/src/main/kotlin/io/rsocket/kotlin/internal/util/Util.kt
> simplify and reduce allocations

- rsocket-core/build.gradle.kts
Combination of things
atomicfu uses FieldUpdaters on Java 8, VarHandler on Java 9+
rsocket-kotlin, kotlin 1.4 is broken on graal (JDK 8)
rsocket-kotlin, kotlin 1.4 works on graal (JDK 11) - if you avoid VarHandles
Hence raising this PR to see how much we care about this optimisation?
> Discuss using field updaters

- .github/workflows/benchmarks.yml
- benchmarks/src/jvmMain/kotlin/io/rsocket/kotlin/benchmarks/RSocketBenchmark.kt
- benchmarks/src/kotlinMain/kotlin/io/rsocket/kotlin/benchmarks/RSocketKotlinBenchmark.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/frame/CancelFrame.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/frame/ErrorFrame.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/frame/ExtensionFrame.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/frame/Frame.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/frame/KeepAliveFrame.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/frame/LeaseFrame.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/frame/MetadataPushFrame.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/frame/RequestFrame.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/frame/RequestNFrame.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/frame/ResumeFrame.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/frame/ResumeOkFrame.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/frame/SetupFrame.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/frame/io/Version.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/frame/io/length.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/frame/io/payload.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/frame/io/util.kt
- rsocket-core/src/commonTest/kotlin/io/rsocket/kotlin/frame/RequestResponseFrameTest.kt
- rsocket-core/src/commonTest/kotlin/io/rsocket/kotlin/frame/ResumeFrameTest.kt
* Use `writePacket` function to use zero copy reading of packets instead of hand written.
Significantly improved performance when working with big payloads.
* Benchmarks updated for comparing different request strategies
> Improve performance for reading of payload

- build.gradle.kts
- rsocket-test/build.gradle.kts
Workaround for not working caching of native debug code. (issue https://youtrack.jetbrains.com/issue/KT-44884)
K/N macos and ios targets support caching in debug builds, but caching not working when using `exclude` for now. Cached builds are much faster.
> add workaround for KT-44884

- examples/multiplatform-chat/build.gradle.kts
- gradle.properties
- playground/build.gradle.kts
- publish-check/build.gradle.kts
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/Connection.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/RSocket.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/internal/RSocketState.kt
- rsocket-core/src/commonTest/kotlin/io/rsocket/kotlin/core/RSocketTest.kt
- rsocket-test/src/commonMain/kotlin/io/rsocket/kotlin/test/InUseTrackingPool.kt
- rsocket-test/src/commonMain/kotlin/io/rsocket/kotlin/test/TestRSocket.kt
- rsocket-test/src/commonMain/kotlin/io/rsocket/kotlin/test/TrackingSet.kt
- rsocket-test/src/commonMain/kotlin/io/rsocket/kotlin/test/TransportTest.kt
- rsocket-test/src/jsMain/kotlin/io/rsocket/kotlin/test/MSet.kt
- rsocket-test/src/jvmMain/kotlin/io/rsocket/kotlin/test/MSet.kt
- rsocket-test/src/nativeMain/kotlin/io/rsocket/kotlin/test/MSet.kt
- rsocket-transport-ktor/src/commonMain/kotlin/io/rsocket/kotlin/transport/ktor/TcpConnection.kt
- rsocket-transport-ktor/src/commonMain/kotlin/io/rsocket/kotlin/transport/ktor/WebSocketConnection.kt
- rsocket-transport-ktor/src/jvmMain/kotlin/io/rsocket/kotlin/transport/ktor/TcpServerTransport.kt
- rsocket-transport-ktor/src/jvmTest/kotlin/io/rsocket/kotlin/JvmTcpTransportTest.kt
- rsocket-transport-ktor/src/jvmTest/kotlin/io/rsocket/kotlin/WebSocketConnectionTest.kt
- rsocket-transport-ktor/src/jvmTest/kotlin/io/rsocket/kotlin/WebSocketTransportTest.kt
- rsocket-transport-local/src/commonTest/kotlin/io/rsocket/kotlin/transport/local/LocalTransportTest.kt
Update ktor version and rework leak tracking mechanism
also keep track for future [KTOR-2442](https://youtrack.jetbrains.com/issue/KTOR-2442)
In ktor 1.5.3 after fix for [KTOR-960](https://youtrack.jetbrains.com/issue/KTOR-960) which under the hood reworks how `ktor-io` works with pools. 
To keep using leak tracking in tests, custom pool need rework.
* ktor 1.5.3 + remove workaround for KTOR-960
* kotlin 1.4.32
* rework leak tracking because of changes in ktor 1.5.3 
* for now uses some `internal` ktor APIs, but only in tests (TODO after [KTOR-2442](https://youtrack.jetbrains.com/issue/KTOR-2442))
* print traces of leaked buffers
* add leak check for all transport tests (previously only `Local` was tested)
* add public `FlowCollector.emitOrClose` WA for absence of operator like …
> ktor 1.5.3 + reworked leak tracking

- examples/multiplatform-chat/src/clientMain/kotlin/Api.kt
- examples/multiplatform-chat/src/serverJvmMain/kotlin/App.kt
- playground/src/commonMain/kotlin/TCP.kt
- playground/src/jvmMain/kotlin/TcpServerApp.kt
- rsocket-transport-ktor/rsocket-transport-ktor-client/src/commonMain/kotlin/io/rsocket/kotlin/transport/ktor/client/Builders.kt
- rsocket-transport-ktor/rsocket-transport-ktor-client/src/commonMain/kotlin/io/rsocket/kotlin/transport/ktor/client/WebSocketClientTransport.kt
- rsocket-transport-ktor/src/commonMain/kotlin/io/rsocket/kotlin/transport/ktor/TcpClientTransport.kt
- rsocket-transport-ktor/src/commonMain/kotlin/io/rsocket/kotlin/transport/ktor/TcpConnection.kt
- rsocket-transport-ktor/src/commonMain/kotlin/io/rsocket/kotlin/transport/ktor/TcpServerTransport.kt
- rsocket-transport-ktor/src/commonTest/kotlin/io/rsocket/kotlin/transport/ktor/TcpServerTest.kt
- rsocket-transport-ktor/src/commonTest/kotlin/io/rsocket/kotlin/transport/ktor/TcpTransportTest.kt
- rsocket-transport-ktor/src/jsMain/kotlin/io/rsocket/kotlin/transport/ktor/readExactPacket.kt
- rsocket-transport-ktor/src/jvmMain/kotlin/io/rsocket/kotlin/transport/ktor/readExactPacket.kt
- rsocket-transport-ktor/src/jvmTest/kotlin/io/rsocket/kotlin/transport/ktor/JvmTcpTransportTest.kt
- rsocket-transport-ktor/src/jvmTest/kotlin/io/rsocket/kotlin/transport/ktor/WebSocketConnectionTest.kt
- rsocket-transport-ktor/src/jvmTest/kotlin/io/rsocket/kotlin/transport/ktor/WebSocketTransportTest.kt
- rsocket-transport-ktor/src/jvmTest/kotlin/io/rsocket/kotlin/transport/ktor/WebSocketTransportTests.kt
- rsocket-transport-ktor/src/nativeMain/kotlin/io/rsocket/kotlin/transport/ktor/readExactPacket.kt
* rework TCP ClientTransport creation for better support of freezing on K/N
* rework TCP ServerTransport creation:
* create TCP server only on bind to RSocketServer
* link socket job and started server
* remove TcpServer class at all
* expose WebSocket client transport as `ClientTransport` interface for parity with tcp
* TCP server now exposed on K/N !!!
* introduce `readExactPacket` - because of [KTOR-2516](https://youtrack.jetbrains.com/issue/KTOR-2516), [KTOR-2519](https://youtrack.jetbrains.com/issue/KTOR-2519), fixes #145
Note: thx to fix for #145 K/N server is now working ok!
> Improve TCP transport

- benchmarks/src/kotlinMain/kotlin/io/rsocket/kotlin/benchmarks/RSocketKotlinBenchmark.kt
- examples/multiplatform-chat/src/serverJvmMain/kotlin/App.kt
- playground/src/commonMain/kotlin/TCP.kt
- playground/src/commonMain/kotlin/WS.kt
- playground/src/jvmMain/kotlin/WSServerApp.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/core/RSocketConnectorBuilder.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/core/ReconnectableRSocket.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/frame/SetupFrame.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/frame/io/Version.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/internal/IntMap.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/internal/RSocketRequester.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/internal/RSocketState.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/internal/flow/LimitingFlowCollector.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/internal/flow/RequestChannelRequesterFlow.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/keepalive/KeepAlive.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/keepalive/KeepAliveHandler.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/metadata/CompositeMetadata.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/metadata/PerStreamAcceptableDataMimeTypesMetadata.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/metadata/RoutingMetadata.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/payload/PayloadMimeType.kt
- rsocket-core/src/commonTest/kotlin/io/rsocket/kotlin/SetupRejectionTest.kt
- rsocket-core/src/commonTest/kotlin/io/rsocket/kotlin/frame/SetupFrameTest.kt
- rsocket-core/src/commonTest/kotlin/io/rsocket/kotlin/frame/io/VersionTest.kt
- rsocket-core/src/jsMain/kotlin/io/rsocket/kotlin/keepalive/currentMillis.kt
- rsocket-core/src/jvmMain/kotlin/io/rsocket/kotlin/keepalive/currentMillis.kt
- rsocket-core/src/nativeMain/kotlin/io/rsocket/kotlin/keepalive/currentMillis.kt
- rsocket-test/src/commonMain/kotlin/io/rsocket/kotlin/test/TransportTest.kt
- rsocket-transport-ktor/rsocket-transport-ktor-client/src/commonMain/kotlin/io/rsocket/kotlin/transport/ktor/client/RSocketSupport.kt
- rsocket-transport-ktor/src/commonMain/kotlin/io/rsocket/kotlin/transport/ktor/TcpConnection.kt
* remove FlowPreview, InternalCoroutinesApi, ExperimentalCoroutinesApi, ExperimentalStdlibApi, ExperimentalUnsignedTypes, ExperimentalTime, KtorExperimentalAPI opt-in usage
* use ordinary class instead of inline for Version
* rewrite KeepAlive to use experimental time only in one place with appropriate annotation, don't use data class
* minor rewrite of PayloadMimeType - change default mime type to "application/octet-stream", don't use data class
fixes #151
> Compatibility improvements

- build.gradle.kts
- rsocket-transport-ktor/src/commonTest/kotlin/io/rsocket/kotlin/transport/ktor/TcpServerTest.kt
- rsocket-transport-ktor/src/jvmTest/kotlin/io/rsocket/kotlin/transport/ktor/JvmTcpTransportTest.kt
- rsocket-transport-ktor/src/nativeTest/kotlin/io/rsocket/kotlin/NativeTcpTransportTest.kt
accidentally TCP tests on JVM were broken in #149 :(
in `TcpServerTest`, additional selectors were created using Default dispatcher and not closed. and as so, after test finished, coroutines will continue working and block threads.
Locally it was not reproducible on my side, as I have 8 cores, but CI has only 2 cores, so I've aligned tests JVM parameters to have better local reproducibility.
> fix jvm tcp freeze in tests

- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/internal/IntMap.kt
fix incorrect IntMap rehash
With intensive parallel calls requestResponse and requestStream with different lifetimes, responses or flow values were sometimes "lost".
Debugging showed that RSocketState.receivers[streamId] sometimes returned null, even though the desired streamId existed.
See diff
The problem is no longer repeated
> fix IntMap.rehash

- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/core/RSocketConnector.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/core/RSocketConnectorBuilder.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/core/RSocketServer.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/core/RSocketServerBuilder.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/internal/Connect.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/internal/FrameSender.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/internal/Prioritizer.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/internal/RSocketRequester.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/internal/RSocketResponder.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/internal/StreamsStorage.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/internal/handler/FrameHandler.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/internal/handler/RequesterRequestChannelFrameHandler.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/internal/handler/RequesterRequestResponseFrameHandler.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/internal/handler/RequesterRequestStreamFrameHandler.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/internal/handler/ResponderFireAndForgetFrameHandler.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/internal/handler/ResponderRequestChannelFrameHandler.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/internal/handler/ResponderRequestResponseFrameHandler.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/internal/handler/ResponderRequestStreamFrameHandler.kt
- rsocket-core/src/commonTest/kotlin/io/rsocket/kotlin/internal/FrameSenderTest.kt
- rsocket-core/src/commonTest/kotlin/io/rsocket/kotlin/internal/PrioritizerTest.kt
- rsocket-core/src/commonTest/kotlin/io/rsocket/kotlin/internal/RSocketRequesterTest.kt
- rsocket-core/src/commonTest/kotlin/io/rsocket/kotlin/internal/handler/RequesterRequestResponseFrameHandlerTest.kt
- rsocket-core/src/commonTest/kotlin/io/rsocket/kotlin/keepalive/KeepAliveTest.kt
- rsocket-core/src/jsMain/kotlin/io/rsocket/kotlin/internal/handler/FrameHandler.kt
- rsocket-core/src/jvmMain/kotlin/io/rsocket/kotlin/internal/handler/FrameHandler.kt
- rsocket-core/src/nativeMain/kotlin/io/rsocket/kotlin/internal/handler/FrameHandler.kt
_**NOTE: Depends on #176**_
* fixes #83 
* move all frame sending functionality into separate class (for future: may be don't use `Frame` class there, and just build final packet with frame, which will be sent to connection)
* implement fragmentation in `FrameSender.sendFragmented` for request frames
* implement simple reassembly logic in `FrameHandler` - TODO some improvements can be added here, like additional checking of consistency like in rsocket-java
* minimal tests added for fragmentation and reassembly - TODO need to add more tests
* TODO need to add more tests for leaked buffers in case of failures
> provides fragmentation and reassembly

- .github/workflows/benchmarks.yml
- .github/workflows/gradle-main.yml
- .github/workflows/gradle-pr.yml
- .github/workflows/gradle-release.yml
- .github/workflows/publish-branch.yml
- .github/workflows/run-tests.yml
https://github.com/gradle/gradle-build-action/releases/tag/v1.4.0
> updates gradle action

- .github/workflows/gradle-main.yml
- .github/workflows/gradle-pr.yml
- .github/workflows/run-tests.yml
- build.gradle.kts
- examples/multiplatform-chat/build.gradle.kts
- playground/build.gradle.kts
- rsocket-test/rsocket-test-server/build.gradle.kts
- rsocket-test/rsocket-test-server/src/jvmMain/kotlin/io/rsocket/kotlin/test/server/App.kt
- rsocket-transport-ktor/build.gradle.kts
- rsocket-transport-ktor/src/jsTest/kotlin/io/rsocket/kotlin/transport/ktor/ClientWebSocketTransportTest.kt
- settings.gradle.kts
_**NOTE: Depends on #178**_
* create infrastructure for client only tests
* implement test for JS WS Client transport
* adapt pipeline to run those tests
> improves client side tests

- .github/workflows/gradle-main.yml
- .github/workflows/gradle-pr.yml
- .github/workflows/gradle-release.yml
- .github/workflows/publish-branch.yml
- .github/workflows/run-tests.yml
- benchmarks/build.gradle.kts
- benchmarks/src/jvmMain/kotlin/io/rsocket/kotlin/benchmarks/RSocketBenchmark.kt
- build.gradle.kts
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/keepalive/KeepAlive.kt
- rsocket-core/src/commonTest/kotlin/io/rsocket/kotlin/core/RSocketTest.kt
- rsocket-core/src/commonTest/kotlin/io/rsocket/kotlin/frame/SetupFrameTest.kt
- rsocket-core/src/commonTest/kotlin/io/rsocket/kotlin/internal/RSocketRequesterTest.kt
- rsocket-core/src/commonTest/kotlin/io/rsocket/kotlin/keepalive/KeepAliveTest.kt
- rsocket-core/src/commonTest/kotlin/io/rsocket/kotlin/metadata/CompositeMetadataTest.kt
- rsocket-test/src/commonMain/kotlin/io/rsocket/kotlin/test/SuspendTest.kt
- rsocket-test/src/commonMain/kotlin/io/rsocket/kotlin/test/TransportTest.kt
* fix code warnings after update
* add missing darwin targets after ktor update
* cleanup gradle versions
* allow skiping link tasks
* use testable watchos target on CI
> Update versions (kotlin 1.6.0, ktor 1.6.7, gradle 7.3.1)

- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/internal/Limiter.kt
- rsocket-core/src/commonTest/kotlin/io/rsocket/kotlin/core/RSocketTest.kt
- rsocket-core/src/commonTest/kotlin/io/rsocket/kotlin/internal/RSocketResponderRequestNTest.kt
This avoids Int overflow when client is misbehaving and is sending multiple RequestN frames with n=Int.MAX_VALUE
This closes #213
Changed AtomicInt to AtomicLong. Overflow is still possible after that, however it will require the client sending a RequestN frame 2147483647 times. Not sure if the request value can become negative under other circumstances. If not, unsigned long can be used instead or the value can be asserted to be positive.
Server won't hang after receiving RequestN frames anymore.
> changed Limiter.requests to AtomicLong

- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/internal/Connect.kt
- rsocket-core/src/commonTest/kotlin/io/rsocket/kotlin/internal/RSocketRequesterTest.kt
fixes: https://github.com/rsocket/rsocket-kotlin/issues/202#issuecomment-1006376408
> Fix closing connection on cancelling requester

- rsocket-transport-tests/src/commonMain/kotlin/io/rsocket/kotlin/transport/tests/TransportTest.kt
Current `TransportTest` is super flaky and a lot of CI failures are because of it...
On current moment I don't want to fix it somehow, as I believe they will be more stable after migrating to new Transport API (with QUIC support) on which Im currently working on.
> ignore flacky tests until new transport API

- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/Annotations.kt
- rsocket-transport-ktor/rsocket-transport-ktor-tcp/src/commonMain/kotlin/io/rsocket/kotlin/transport/ktor/tcp/TcpConnection.kt
- rsocket-transport-local/src/commonMain/kotlin/io/rsocket/kotlin/transport/local/LocalServer.kt
- rsocket-transport-nodejs-tcp/src/jsMain/kotlin/io/rsocket/kotlin/transport/nodejs/tcp/FrameWithLengthAssembler.kt
- rsocket-transport-nodejs-tcp/src/jsMain/kotlin/io/rsocket/kotlin/transport/nodejs/tcp/TcpConnection.kt
This is mostly pro-active PR to support compilation with Kotlin K2 compiler.
Tested with Kotlin version 1.9.0-Beta-104.
Changes don't affect old K1 compiler, so it's safe.
> compatibility with K2 compiler

- .gitignore
- .idea/codeStyles/Project.xml
- .idea/codeStyles/codeStyleConfig.xml
- .idea/copyright/Apache_2_0.xml
- .idea/copyright/profiles_settings.xml
- .idea/vcs.xml
After this changes, there will be no need for other maintainers (or contributors) to configure code style or copyright logic if they use IDEA.
> add idea codestyle and copyright config

- .github/workflows/run-tests.yml
- buildSrc/src/main/kotlin/targetsNative.kt
- gradle.properties
* Kotlin JS Legacy compiler was deprecated in Kotlin 1.8.0 - https://kotlinlang.org/docs/js-overview.html#kotlin-js-ir-compiler
* iosArm32 and watchosX86 were deprecated in Kotlin 1.8.20 - https://kotlinlang.org/docs/native-target-support.html#deprecated-targets
* Both will be removed/errored in Kotlin 1.9.0 or 1.9.20
fixes #230
> drop JS legacy and deprecated native targets

- rsocket-core/build.gradle.kts
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/frame/io/payload.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/internal/CloseOperations.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/internal/Prioritizer.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/internal/RSocketRequester.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/internal/handler/RequesterRequestChannelFrameHandler.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/internal/handler/RequesterRequestStreamFrameHandler.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/internal/handler/ResponderRequestChannelFrameHandler.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/metadata/CompositeMetadata.kt
- rsocket-core/src/commonTest/kotlin/io/rsocket/kotlin/TestConnection.kt
- rsocket-core/src/commonTest/kotlin/io/rsocket/kotlin/frame/Util.kt
- rsocket-internal-io/api/rsocket-internal-io.api
- rsocket-internal-io/build.gradle.kts
- rsocket-internal-io/src/commonMain/kotlin/io/rsocket/kotlin/internal/io/Channels.kt
- rsocket-internal-io/src/commonMain/kotlin/io/rsocket/kotlin/internal/io/Int24.kt
- rsocket-transport-ktor/rsocket-transport-ktor-tcp/build.gradle.kts
- rsocket-transport-ktor/rsocket-transport-ktor-tcp/src/commonMain/kotlin/io/rsocket/kotlin/transport/ktor/tcp/TcpConnection.kt
- rsocket-transport-ktor/rsocket-transport-ktor-websocket-client/build.gradle.kts
- rsocket-transport-ktor/rsocket-transport-ktor-websocket-server/build.gradle.kts
- rsocket-transport-local/build.gradle.kts
- rsocket-transport-local/src/commonMain/kotlin/io/rsocket/kotlin/transport/local/LocalServer.kt
- rsocket-transport-nodejs-tcp/src/jsMain/kotlin/io/rsocket/kotlin/transport/nodejs/tcp/FrameWithLengthAssembler.kt
- rsocket-transport-nodejs-tcp/src/jsMain/kotlin/io/rsocket/kotlin/transport/nodejs/tcp/TcpConnection.kt
- settings.gradle.kts
New module is a support module for core and transport implementations.
This allows to drop using internal declarations, as well as not exposing it to library consumers, until explicitly requested
Depends on: #244
> introduce new module `rsocket-internal-io`

- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/frame/io/mimeType.kt
- rsocket-core/src/commonTest/kotlin/io/rsocket/kotlin/frame/io/MimeTypeTest.kt
- rsocket-core/src/commonTest/kotlin/io/rsocket/kotlin/frame/io/Util.kt
Adjust MIME type name length serialization to ensure compatibility with other RSocket implementations.
> Fix custom MIME type serialization incompatibility (#260)

- README.md
update version to 0.16.0 in README.md
> Prepare for 0.16.0

- .github/workflows/publish-release.yml
- .github/workflows/publish-snapshot.yml
- build-logic/build.gradle.kts
- build-logic/src/main/kotlin/rsocketbuild.publication.gradle.kts
- gradle.properties
- gradle/libs.versions.toml
It creates staging repository itself and doesn't rely on auto-staging
> use `gradle-maven-publish-plugin`

- gradle/libs.versions.toml
- rsocket-transports/netty-internal/api/rsocket-transport-netty-internal.api
- rsocket-transports/netty-internal/build.gradle.kts
- rsocket-transports/netty-internal/src/jvmMain/kotlin/io/rsocket/kotlin/transport/netty/internal/coroutines.kt
- rsocket-transports/netty-quic/api/rsocket-transport-netty-quic.api
- rsocket-transports/netty-quic/build.gradle.kts
- rsocket-transports/netty-quic/src/jvmMain/kotlin/io/rsocket/kotlin/transport/netty/quic/NettyQuicClientTransport.kt
- rsocket-transports/netty-quic/src/jvmMain/kotlin/io/rsocket/kotlin/transport/netty/quic/NettyQuicConnectionHandler.kt
- rsocket-transports/netty-quic/src/jvmMain/kotlin/io/rsocket/kotlin/transport/netty/quic/NettyQuicConnectionInitializer.kt
- rsocket-transports/netty-quic/src/jvmMain/kotlin/io/rsocket/kotlin/transport/netty/quic/NettyQuicServerTransport.kt
- rsocket-transports/netty-quic/src/jvmMain/kotlin/io/rsocket/kotlin/transport/netty/quic/NettyQuicStreamHandler.kt
- rsocket-transports/netty-quic/src/jvmMain/kotlin/io/rsocket/kotlin/transport/netty/quic/NettyQuicStreamInitializer.kt
- rsocket-transports/netty-quic/src/jvmTest/kotlin/io/rsocket/kotlin/transport/netty/quic/NettyQuicTransportTest.kt
- rsocket-transports/netty-tcp/api/rsocket-transport-netty-tcp.api
- rsocket-transports/netty-tcp/build.gradle.kts
- rsocket-transports/netty-tcp/src/jvmMain/kotlin/io/rsocket/kotlin/transport/netty/tcp/NettyTcpClientTransport.kt
- rsocket-transports/netty-tcp/src/jvmMain/kotlin/io/rsocket/kotlin/transport/netty/tcp/NettyTcpConnectionHandler.kt
- rsocket-transports/netty-tcp/src/jvmMain/kotlin/io/rsocket/kotlin/transport/netty/tcp/NettyTcpConnectionInitializer.kt
- rsocket-transports/netty-tcp/src/jvmMain/kotlin/io/rsocket/kotlin/transport/netty/tcp/NettyTcpServerTransport.kt
- rsocket-transports/netty-tcp/src/jvmTest/kotlin/io/rsocket/kotlin/transport/netty/tcp/NettyTcpTransportTest.kt
- rsocket-transports/netty-websocket/api/rsocket-transport-netty-websocket.api
- rsocket-transports/netty-websocket/build.gradle.kts
- rsocket-transports/netty-websocket/src/jvmMain/kotlin/io/rsocket/kotlin/transport/netty/websocket/NettyWebSocketClientTransport.kt
- rsocket-transports/netty-websocket/src/jvmMain/kotlin/io/rsocket/kotlin/transport/netty/websocket/NettyWebSocketConnectionHandler.kt
- rsocket-transports/netty-websocket/src/jvmMain/kotlin/io/rsocket/kotlin/transport/netty/websocket/NettyWebSocketConnectionInitializer.kt
- rsocket-transports/netty-websocket/src/jvmMain/kotlin/io/rsocket/kotlin/transport/netty/websocket/NettyWebSocketServerTransport.kt
- rsocket-transports/netty-websocket/src/jvmTest/kotlin/io/rsocket/kotlin/transport/netty/websocket/NettyWebSocketTransportTest.kt
- settings.gradle.kts
* QUIC implementation is still WIP and will be improved later, after better/more tests will be written for transports
> Netty TCP, WebSocket and QUIC transports

- build-logic/src/main/kotlin/rsocketbuild.multiplatform-base.gradle.kts
- build-logic/src/main/kotlin/rsocketbuild/OptIns.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/Annotations.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/Connection.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/connection/OldConnection.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/core/InterceptorsBuilder.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/core/RSocketConnector.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/core/RSocketServer.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/transport/ClientTransport.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/transport/ServerTransport.kt
- rsocket-core/src/commonTest/kotlin/io/rsocket/kotlin/core/RSocketTest.kt
- rsocket-transport-tests/src/commonMain/kotlin/io/rsocket/kotlin/transport/tests/TransportTest.kt
- rsocket-transports/ktor-tcp/src/commonMain/kotlin/io/rsocket/kotlin/transport/ktor/tcp/TcpClientTransport.kt
- rsocket-transports/ktor-tcp/src/commonMain/kotlin/io/rsocket/kotlin/transport/ktor/tcp/TcpConnection.kt
- rsocket-transports/ktor-tcp/src/commonMain/kotlin/io/rsocket/kotlin/transport/ktor/tcp/TcpServerTransport.kt
- rsocket-transports/ktor-tcp/src/commonTest/kotlin/io/rsocket/kotlin/transport/ktor/tcp/TcpTransportTest.kt
- rsocket-transports/ktor-websocket-client/src/commonMain/kotlin/io/rsocket/kotlin/transport/ktor/websocket/client/WebSocketClientTransport.kt
- rsocket-transports/ktor-websocket-internal/src/commonMain/kotlin/io/rsocket/kotlin/transport/ktor/websocket/internal/WebSocketConnection.kt
- rsocket-transports/ktor-websocket-server/src/commonMain/kotlin/io/rsocket/kotlin/transport/ktor/websocket/server/WebSocketServerTransport.kt
- rsocket-transports/ktor-websocket-server/src/commonTest/kotlin/io/rsocket/kotlin/transport/ktor/websocket/server/WebSocketTransportTest.kt
- rsocket-transports/local/src/commonMain/kotlin/io/rsocket/kotlin/transport/local/LocalConnection.kt
- rsocket-transports/local/src/commonMain/kotlin/io/rsocket/kotlin/transport/local/LocalServer.kt
- rsocket-transports/local/src/commonTest/kotlin/io/rsocket/kotlin/transport/local/LocalTransportTest.kt
- rsocket-transports/nodejs-tcp/src/jsMain/kotlin/io/rsocket/kotlin/transport/nodejs/tcp/TcpClientTransport.kt
- rsocket-transports/nodejs-tcp/src/jsMain/kotlin/io/rsocket/kotlin/transport/nodejs/tcp/TcpConnection.kt
- rsocket-transports/nodejs-tcp/src/jsMain/kotlin/io/rsocket/kotlin/transport/nodejs/tcp/TcpServerTransport.kt
- rsocket-transports/nodejs-tcp/src/jsTest/kotlin/io/rsocket/kotlin/transport/nodejs/tcp/TcpTransportTest.kt
* Old transport implementations are deprecated for removal in next release
> Deprecate old transport API for removal in next release

- ktor-plugins/ktor-tests/src/commonTest/kotlin/io/rsocket/kotlin/ktor/tests/WebSocketConnectionTest.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/RSocket.kt
- rsocket-core/src/commonTest/kotlin/io/rsocket/kotlin/core/RSocketTest.kt
- rsocket-transport-tests/src/commonMain/kotlin/io/rsocket/kotlin/transport/tests/TransportTest.kt
With current kotlinx.io it's not that problematic not to release buffers and so it's better to remove this strange function. In any case, it will not handle all issues with uncleared buffers
> Deprecate emitOrClose

- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/connection/ConnectionInbound.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/connection/ConnectionInitializer.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/connection/MultiplexedConnection.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/connection/SequentialConnection.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/core/RSocketConnector.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/core/RSocketServer.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/frame/Frame.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/frame/FrameCodec.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/frame/RequestFrame.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/frame/SetupFrame.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/internal/IntMap.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/internal/PayloadAssembler.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/internal/PayloadChannel.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/operation/OperationInbound.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/operation/OperationOutbound.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/operation/RequesterRequestChannelOperation.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/operation/RequesterRequestResponseOperation.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/operation/ResponderRequestChannelOperation.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/transport/internal/PrioritizationFrameQueue.kt
- rsocket-core/src/commonTest/kotlin/io/rsocket/kotlin/core/RSocketTest.kt
- rsocket-core/src/commonTest/kotlin/io/rsocket/kotlin/operation/RequesterRequestResponseOperationTest.kt
- rsocket-internal-io/src/commonMain/kotlin/io/rsocket/kotlin/internal/io/Channels.kt
- rsocket-transport-tests/src/commonMain/kotlin/io/rsocket/kotlin/transport/tests/TransportTest.kt
- rsocket-transports/ktor-tcp/src/commonMain/kotlin/io/rsocket/kotlin/transport/ktor/tcp/KtorTcpClientTransport.kt
- rsocket-transports/netty-internal/src/jvmMain/kotlin/io/rsocket/kotlin/transport/netty/internal/io.kt
- rsocket-transports/nodejs-tcp/src/jsMain/kotlin/io/rsocket/kotlin/transport/nodejs/tcp/TcpConnection.kt
- rsocket-transports/nodejs-tcp/src/jsTest/kotlin/io/rsocket/kotlin/transport/nodejs/tcp/TcpTransportTest.kt
recheck all TODOs before release
> Drop or rename TODOs (issues will be created) and use logging for unexpected frame

- rsocket-core/api/rsocket-core.api
- rsocket-core/api/rsocket-core.klib.api
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/RSocketRequestHandler.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/frame/ErrorFrame.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/frame/ExtensionFrame.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/frame/KeepAliveFrame.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/frame/LeaseFrame.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/frame/MetadataPushFrame.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/frame/RequestFrame.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/frame/RequestNFrame.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/frame/ResumeFrame.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/frame/ResumeOkFrame.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/frame/SetupFrame.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/frame/io/Version.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/frame/io/mimeType.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/frame/io/payload.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/frame/io/util.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/metadata/CompositeMetadata.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/metadata/CompositeMetadataExtensions.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/metadata/Metadata.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/metadata/PerStreamAcceptableDataMimeTypesMetadata.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/metadata/PerStreamDataMimeTypeMetadata.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/metadata/RawMetadata.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/metadata/RoutingMetadata.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/metadata/ZipkinTracingMetadata.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/metadata/security/AuthMetadata.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/metadata/security/BearerAuthMetadata.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/metadata/security/RawAuthMetadata.kt
- rsocket-core/src/commonMain/kotlin/io/rsocket/kotlin/metadata/security/SimpleAuthMetadata.kt
- rsocket-core/src/commonTest/kotlin/io/rsocket/kotlin/transport/internal/PrioritizationFrameQueueTest.kt
`Buffer` currently should be used everywhere, as a contract. Currently, we should not be able to use sources which are backed by files or similar, as they could block the running thread, which is currently unacceptable.
Should be investigated further later: https://github.com/rsocket/rsocket-kotlin/issues/110
> Remove usage of `Source` where missed, as for now the main primitive should be `Buffer`

- .github/workflows/publish-snapshot.yml
- README.md
- gradle.properties
The release contains a lot of changes, both breaking and features wise, so the next release will be 0.20.0 - like a "major" bump :)
> Update README and prepare for the 0.20.0 release
